### ISSUE TITLE
DS1819+, USB lan lost after reboot

### ISSUE THREAD

**Issue by neoswatty** [bb-qq/r8152#10]
### Description of the problem
DS1819+, USB lan device lost after reboot, but can be restored by manually stop and start the RTL driver package in package center.

### Description of your products
Linux Orion 4.4.59+ #24922 SMP PREEMPT Tue Jan 14 15:20:58 CST 2020 x86_64 GNU/Linux synology_denverton_1819+
DSM 6.22.2-24922 update 5
Asustor AS-U2.5G dongle

### Description of your environment
attached dmesg.
[dmesg.txt](https://github.com/bb-qq/r8152/files/4230344/dmesg.txt)
The symptom is that when the NAS boots up, the eth4 (USB lan) is not found by command ifconfig -a.
but after manually stop and start the RTL driver package in package center, the eth4 show up and the additional lan can be found on control panel.
In the dmesg, I tried to restart the package @ 2xx sec.
synoservice --restart pkgctl-r8152 also make the usb lan works.

**Comment by bb-qq** [comment]
This issue should be fixed by this version: https://github.com/bb-qq/r8152/releases/tag/2.12.0-3

**Comment by bb-qq** [comment]
Some users reported this kind of bug is fixed. Please feel free to re-open this issue if problems remained.
