### ISSUE TITLE
No connection after reboot NAS 918

### ISSUE THREAD

**Issue by chenlei630** [bb-qq/r8152#108]

**Comment by chenlei630** [comment]
It could be worked well after resetting new IP in the NAS for each new connection. Do you have any solution for the resetting new IP. Thank you.

**Comment by bb-qq** [comment]
Could you try this workaround?
https://github.com/bb-qq/r8152/issues/92#issuecomment-783863386

**Comment by Gensplejs** [comment]
Are you using static IP or automatic (DHCP)

**Comment by bb-qq** [comment]
DHCP bug was fixed in release 2.14.0-3. Please feel free to re-open the issue if you still have the issue.
