### ISSUE TITLE
DS1821+ not working

### ISSUE THREAD

**Issue by CookieSir** [bb-qq/r8152#109]
ds1821 
Install r8152-v1000-2.14.0-2a.spk
If you click Start multiple times in the Package Center, the driver cannot be started, and the page shows the disabled status.

**Comment by Sjekke** [comment]
> ds1821 
> 
> Cannot start after installation

You hope to have reply? 

What cannot start? You ethernet card, your NAS, your driver? 
What???

**Comment by joejohnson1701** [comment]
> > ds1821
> > 安装后无法启动
> 
> 您希望得到答复？
> 
> 什么不能开始？您的以太网卡，您的NAS，您的驱动程序？
> 什么？？？

r8152-v1000-2.14.0-2a.spk
After installing the package center, the r8152 driver cannot be started

**Comment by joejohnson1701** [comment]
> > ds1821
> > Cannot start after installation
> 
> You hope to have a reply?
> 
> What cannot start? You ethernet card, your NAS, your driver?
> What???

r8152-v1000-2.14.0-2a.spk
After installing the package center, the r8152 driver cannot be started

**Comment by bertybassett** [comment]
the applications is running on my 1821+ however I am still awaiting delivery of my card.

**Comment by bb-qq** [comment]
This loding issues was fixed in the 2.14.0-2b release. Please create a new issue if that has another problem.
