### ISSUE TITLE
DS1817+ Two RTL8153 connection

### ISSUE THREAD

**Issue by a4771107** [bb-qq/r8152#110]
![2021-03-20 21_17_01-Window](https://user-images.githubusercontent.com/81021011/111869325-345b6e00-89c2-11eb-906e-e857a7578ea0.png)

![2021-03-20 21_23_10-Window](https://user-images.githubusercontent.com/81021011/111869407-a5028a80-89c2-11eb-9267-5864af1b1222.png)

Two RTL8153 connection
Only one is recognized normally
In the device information, one is recognized as an 8152 USB DISK.
8153 Is there a way to recognize the two normally?

**Comment by bb-qq** [comment]
Could you try this workaround?
https://github.com/bb-qq/r8152/issues/92#issuecomment-783863386

**Comment by a4771107** [comment]
I can't find a workaround, but thanks.
