### ISSUE TITLE
DS1817+ USB LAN card cannot be used in VMM

### ISSUE THREAD

**Issue by a4771107** [bb-qq/r8152#111]
![2021-03-20 21_27_45-Window](https://user-images.githubusercontent.com/81021011/111869528-56a1bb80-89c3-11eb-8ded-4dc6f462a5b1.png)

Is there any way I can use it in VMM?

**Comment by bb-qq** [comment]
This is a limitation of the driver currently. The workaround is written here.
https://github.com/bb-qq/r8152/issues/90#issue-794013966

**Comment by a4771107** [comment]
I solved it, but it still doesn't work on reboot.
But I am satisfied enough
Many Korean friends are getting help
Thank you to the faceless hero

**Comment by a4771107** [comment]
https://cafe.naver.com/synologynas
Korea exchanges information here
For many members here you are hope

**Comment by bb-qq** [comment]
The latest driver does support the Open vSwitch(VMM) feature. Please try it. If you have any issues, create a new issue.
