### ISSUE TITLE
Will it appear in dsm7 in the future?

### ISSUE THREAD

**Issue by akimolll** [bb-qq/r8152#113]
This is really wonderful. It has saved a lot of people! Will it appear in the future installed version of dsm7? I hope this day will come as soon as possible, dsm7 is the future! Always support!

**Comment by Gensplejs** [comment]
I just tested with DSM7.
The package is disabled after the update and when uninstalled it and then attempted to reinstall is says the package is in an invalid file format.

**Comment by bb-qq** [comment]
Duplicate of #26 # #
