### ISSUE TITLE
Driver request for 88f628x

### ISSUE THREAD

**Issue by alphacoc** [bb-qq/r8152#117]
Would you mind compiling the driver for 88f628x architectures? Thanks!

**Comment by bb-qq** [comment]
I have tried to build the driver for the 6218 architecture, but Realtek seems not to support the kernel version 2.6.32 used by 88f628x.
https://github.com/SynologyOpenSource/pkgscripts-ng/blob/master/include/platforms

**Comment by bb-qq** [comment]
Even if I can port the driver to the old kernel, I suspect that the xHCI host controller driver will not work properly with the kernel. So I am going to close this issue.
