### ISSUE TITLE
Would it be possbile to make it work on DSM 6.1.7?

### ISSUE THREAD

**Issue by topcheer** [bb-qq/r8152#12]
Has anyone tried to tweak this?

**Comment by topcheer** [comment]
I have managed to compile the source with 6.1 SDK,  it actually worked well.

![image](https://user-images.githubusercontent.com/1550007/77641123-7bbd4300-6f96-11ea-898d-042ccb1b193d.png)

**Comment by Gankyo** [comment]
I need it！Send me Please~~~~
Please~~~~
Please~~~~
Please~~~~
ganky@126.com

**Comment by YXHTom** [comment]
I also need it！Send me Please
765888697@qq.com
