### ISSUE TITLE
Add alpine4k support (e.g. 416)

### ISSUE THREAD

**Issue by deveth0** [bb-qq/r8152#126]
Hey, is there any chance to get builds for alpine4k architecture (e.g. DS416)?

```
Linux backupstation 3.10.105 #25556 SMP Thu Mar 4 17:49:58 CST 2021 armv7l GNU/Linux synology_alpine4k_ds416
```

If i get it right, this should alread work as you added the required fallbacks for 3.10.x here:
https://github.com/bb-qq/r8152/commit/1f24cbbce59db74f7aeef2458d76ae209c753af4

**Comment by sftt** [comment]
DS215+ also apline4k, Thanks.
Linux mynas 3.10.105 #25556 SMP Thu Mar 4 17:49:58 CST 2021 armv7l GNU/Linux synology_alpine4k_ds215+
Linux version 3.10.105 (root@build1) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25556 SMP Thu Mar 4 17:49:58 CST 2021

**Comment by helsinkii** [comment]
DS416 apline4k, thanks

**Comment by bb-qq** [comment]
I added the support of alpine4k from the release for DSM 7.0. Is it enough?

**Comment by deveth0** [comment]
Awesome, thanks! Good reason to upgrade :)

**Comment by helsinkii** [comment]
can't install the driver on DSM7 from the SSH terminal
install: cannot stat '/var/packages/r8152/target/r8152/spk_su': No such file or directory

**Comment by bb-qq** [comment]
> install: cannot stat '/var/packages/r8152/target/r8152/spk_su': No such file or directory

It seems that spk has not been installed.
Did you proceed to the point where the Package Manager shows an error?

**Comment by helsinkii** [comment]
> > install: cannot stat '/var/packages/r8152/target/r8152/spk_su': No such file or directory
> 
> It seems that spk has not been installed.
> Did you proceed to the point where the Package Manager shows an error?

Sorry, it seems that I mixed up alpine with alpine4k.  Have the driver for alpine4k been released? I can't find It.

**Comment by bb-qq** [comment]
Build outputs produced by SDK of alpine4k has the same architecture name `alpine` in spk. So I believe that -alpine.spk works for your model. If not, please let me know.

**Comment by helsinkii** [comment]
> > install: cannot stat '/var/packages/r8152/target/r8152/spk_su': No such file or directory
> 
> It seems that spk has not been installed.
> Did you proceed to the point where the Package Manager shows an error?

DS416, DSM 7.0, manually uploaded "r8152-alpine-2.15.0-3.spk" in package center ,  pop-up message "the package is not supported on the platform of Diskstation or is incompattible with the current DSM version."

**Comment by bb-qq** [comment]
I created two versions of the package to investigate this issue. Could you try both?
https://github.com/bb-qq/r8152/releases/download/2.15.0-3/r8152-alpine4k-2.15.0-3.spk
https://github.com/bb-qq/r8152/releases/download/2.15.0-3/r8152-alpine4k_test-2.15.0-3.spk

**Comment by helsinkii** [comment]
> I created two versions of the package to investigate this issue. Could you try both?
> https://github.com/bb-qq/r8152/releases/download/2.15.0-3/r8152-alpine4k-2.15.0-3.spk
> https://github.com/bb-qq/r8152/releases/download/2.15.0-3/r8152-alpine4k_test-2.15.0-3.spk

I tried the first one, it worked. Will try the second one this week.

**Comment by bb-qq** [comment]
I am adopting the first one as the official release. If you have any problems, please create a new issue.
