### ISSUE TITLE
Request add support for the USB Lan Card(DS918 +)R8156

### ISSUE THREAD

**Issue by nobita0464** [bb-qq/r8152#127]
Model : Synology DS918+
Firmware: DSM 6.2.4-255556
USB Lan ID: 
0bda:8156:3100 00  2.10  480MBit/s 200mA 1IF  (Realtek USB 10/100/1G/2.5G LAN 001000001)

**Comment by bb-qq** [comment]
Could you post the output of `dmesg`?

**Comment by ikanfilm** [comment]
DS918+ installed on unRAID, direct through USB 3.0 Adapter to DSM VM, after install 2.14.03, it doesn't work
ID 0bda:8156 Realtek Semiconductor Corp. USB 10/100/1G/2.5G LAN

**Comment by bb-qq** [comment]
This VID/PID is already supported. So it seems to be installation problems. I need further information.

**Comment by bb-qq** [comment]
I close this issue, but if still have any problems, please feel free to reopen the issue.
