### ISSUE TITLE
Confirmed working with plugable 2.5 Gbps USB Ethernet Adapter USBC-E2500 DS1815+

### ISSUE THREAD

**Issue by mervincm** [bb-qq/r8152#14]
I had to up the USB nic with "sudo ifconfig eth4 up" and then set to DHCP in the Synology GUI portal.

**Comment by mervincm** [comment]
also does not keep ifconfig after restart. I have to up the NIC with a shellscript at each boot w a sleep delay, then reconfigure it.

**Comment by megabyte0469** [comment]
reboot script with "synoservice --restart pkgctl-r8152" resolved this problem.

**Comment by mervincm** [comment]
thanks, I will try that!

**Comment by mervincm** [comment]
works perfect, thanks for that!

**Comment by megabyte0469** [comment]
ok, by ethernet bond with the adapter help this script:

synoservice --restart pkgctl-r8152
sleep 5
/etc/rc.network restart
sleep 5

**Comment by bb-qq** [comment]
The topic about bond is discussed in #17.
