### ISSUE TITLE
DS418 with 8156B

### ISSUE THREAD

**Issue by stcssk** [bb-qq/r8152#141]
The 2.5G network card is configured successfully, but the data cannot be transmitted from the 2.5G network port, which will cause the NAS down.

**Comment by stcssk** [comment]
DSM7.0

**Comment by bb-qq** [comment]
To summarize the reports in this forum, it seems that the USB controller of the RTD1296 platform has a flaw that prevents this driver from working stably.

It's odd that it doesn't work with the RealTek hardware, but there doesn't seem to be anything I can do about it at the moment. Sorry.

**Comment by bb-qq** [comment]
I created an experimental driver with low memory consumption. Could you try this?
https://github.com/bb-qq/r8152/releases/download/2.15.0-5/r8152-rtd1296-2.15.0-6_rxbuf-test.spk

**Comment by stcssk** [comment]
您好，我已收到您的邮件，我会尽快查看并处理，辛苦了，谢谢！~

**Comment by stcssk** [comment]
Very thx.I will try in few days！Devices are not nearby now.thx！！



---Original---
From: ***@***.***&gt;
Date: Sat, Feb 5, 2022 17:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bb-qq/r8152] DS418 with 8156B (#141)




 
I created an experimental driver with low memory consumption. Could you try this?
 https://github.com/bb-qq/r8152/releases/download/2.15.0-5/r8152-rtd1296-2.15.0-6_rxbuf-test.spk
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bb-qq** [comment]
I decided to merge topics on rtd1296 into issue #275.
If you notice anything new, please comment there.

**Comment by stcssk** [comment]
您好，我已收到您的邮件，我会尽快查看并处理，辛苦了，谢谢！~
