### ISSUE TITLE
Disappear in DSM network adapter after reboot

### ISSUE THREAD

**Issue by rickywu** [bb-qq/r8152#144]
The first time I install it when use Proxmox VE pass USB device to VM works well, but after reboot,
lsusb list it but not appear in DSM network adapter.

I verified this works

01:1b.0) hub
  |__2-1         0bda:815**6**:3000 00  3.20 5000MBit/s 512mA 1IF  (Realtek USB 10/100/1G/2.5G LAN 000000001)

but this not work:

01:1b.0) hub
  |__2-1         0bda:815**1**:3000 00  3.20 5000MBit/s 512mA 1IF  (Realtek USB 10/100/1G/2.5G LAN 000000001)

### Description of your products

Linux NAS 4.4.59+ #25426 SMP PREEMPT Tue May 12 04:54:55 CST 2020 x86_64 GNU/Linux synology_apollolake_918+
DSM version 6.2.3
UGreen 2.5G

### Output of ``ifconfig -a`` command

````
eth0      Link encap:Ethernet  HWaddr 00:11:32:12:34:56
          inet addr:192.168.0.3  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::211:32ff:fe12:3456/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:75534 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6076 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:82621839 (78.7 MiB)  TX bytes:2431354 (2.3 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:82 errors:0 dropped:0 overruns:0 frame:0
          TX packets:82 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:18958 (18.5 KiB)  TX bytes:18958 (18.5 KiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````

**Comment by rickywu** [comment]
It disapear again, do you know the reason?

**Comment by bb-qq** [comment]
Could you try to increase the delay of loading driver written in `/var/packages/r8152/scripts/start-stop-status`? `sleep 15` is it.

**Comment by fallaha56** [comment]
Hi guys, similar problem here but just a good old fashioned reboot into DSM 6.2 is enough to make the 8156 adaptor disappear

Any suggestions how to make the Syno see it on reboot without having to disconnect network cables and stop/start the driver manually?

**Comment by fallaha56** [comment]
Do I have to modify the driver script and then re-upload?

> Could you try to increase the delay of loading driver written in `/var/packages/r8152/scripts/start-stop-status`? `sleep 15` is it.

Am I supposed to modify the script then re-upload the driver?

Thanks -and sorry for my n00bness here

**Comment by rickywu** [comment]
I already changed to 15s and seems my USB address changed so DSM cannot recongize it
I'll try to find the reason why address changed and verify this problem again.

**Comment by rickywu** [comment]
@bb-qq 
I changed to 20s still has this problem
lsusb shows that USB device with correct product id and ip a s nothing found

**Comment by rickywu** [comment]
I solved by install drivers in pve host os, after that it can be recognozed correcttly

```
apt install dwarves
apt install pve-headers-5.11.22-1-pve/now build-essential dkms
cp /sys/kernel/btf/vmlinux /usr/lib/modules/`uname -r`/build/

#install by compile
make
make install
mkdir -p /lib/modules/`uname -r`/kernel/net/usb
cp /root/r8152-2.15.0/r8152.ko /lib/modules/`uname -r`/kernel/net/usb/
#must install rules
make install_rules
depmod -a
update-initramfs -u

#install by dkms
dkms add -m r8125 -v 2.15.0
dkms build -m r8125 -v 2.15.0
dkms install -m r8125 -v 2.15.0
depmod -a
modprobe r8125

#load for reboot
echo "r8152" | sudo tee /etc/modules-load.d/r8152.conf

#reboot and check
lsmod | grep 'r8152'
```
