### ISSUE TITLE
Privilege escalation with DSM7

### ISSUE THREAD

**Issue by Benares1** [bb-qq/r8152#146]
bb-qq did a lot of work to establish privilege escalation for DSM7 with spk_su.c

Isn't it possible to make this much more easier by using a ctrl-script section in conf/privilege? I saw this with other packages like FileStation ...

`        "defaults":{
                "run-as": "package"
        },
        "ctrl-script":[{
                "action": "postinst",
                "run-as": "root"
        }, {
                "action": "preinst",
                "run-as": "root"
        }, {
                "action": "postuninst",
                "run-as": "root"
        }, {
                "action": "postupgrade",
                "run-as": "root"
        }, {
                "action": "preupgrade",
                "run-as": "root"
        }, {
                "action": "start",
                "run-as": "root"
        }, {
                "action": "stop",
                "run-as": "root"
        }, {
                "action": "status",
                "run-as": "root"
        }],
...`

**Comment by bb-qq** [comment]
`"run-as": "root" ` configuration is only allowed to Synology packages. Please see #137 for details. If you have further questions, please feel free to re-open this issue.
