### ISSUE TITLE
1621+ Compatibility?

### ISSUE THREAD

**Issue by Geddart** [bb-qq/r8152#148]
Hey there, I was using this driver successfully on two 918+ Devices but I'm thinking about switching to a 1621+ with a Ryzen Processor. Would this driver work as well?

**Comment by Sjekke** [comment]
If you can afford a Ds1621+, why not install a PCIE 10gb-card ... no trouble with drivers.

**Comment by Geddart** [comment]
I have the 2.5Gbe Adapter but you're right - the E10G18-T1 is a better, more future-proof (10Gbe) solution.

**Comment by Sjekke** [comment]
🤙

**Comment by bb-qq** [comment]
Yes, the driver of v1000 can be loaded for this product and some users reported it works.
However, for stability, I would also strongly recommend using a PCIe-based interface as well.

If you want to save money, you can use AQC107 based compatible NICs such as [ASUS XG-C100C ](https://amzn.to/3lXFdNu) or [TPLINK TX401](https://amzn.to/2XN6x9r).
