### ISSUE TITLE
package r8152-rtd1296_for_2GB_RAM-2.15.0-4.spk 

### ISSUE THREAD

**Issue by daveyeger** [bb-qq/r8152#159]
Hi @bb-qq ,

I  installed this package on a DS218.

It is definitely more stable than the prior version.

One issue I noticed, the  NIC does not show up after a reboot.

I can easily get it back with ifconfig eth1 up && synonet --dhcp eth1.

Not sure what I am doing wrong.

Thanks for getting all of this work done!

**Comment by bb-qq** [comment]
@daveyeger , could you try to increase the delay of loading driver written in /var/packages/r8152/scripts/start-stop-status? sleep 15 is it.

@HAuser2019, could you create a new issue using the bug report template? I want to see the output of `demsg`.

**Comment by bb-qq** [comment]
The latest driver 2.15.0-5 has improved start-up handling. so could you try it?
Since I haven't heard back from you, I'm closing this issue, but feel free to reopen it if you still have any problems.

**Comment by HAuser2019** [comment]
Sorry. I read in another threat that you gave up on this particular driver/model, so at some point I forgot this treat. I will try the new driver in a few weeks and if I ran in an issue I will open it up, using bug report template output demsg etc. Thanks
