### ISSUE TITLE
package is not supported on the platform of synology NAS 920+

### ISSUE THREAD

**Issue by saihua** [bb-qq/r8152#168]

**Comment by sfth-golf** [comment]
No luck on my 920+ either. Appears as package running, but device not listed.

**Comment by saihua** [comment]
mine is good now. I use r8152-geminilake-2.15.0-4.spk and use https://www.amazon.com/gp/product/B093FB9QWB/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1
https://www.amazon.com/gp/product/B07VNFLTLD/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

they both works. You will need to restart 920+
