### ISSUE TITLE
Add parameter to Start Script the driver works with Bond configuration too

### ISSUE THREAD

**Issue by megabyte0469** [bb-qq/r8152#17]
Hallo,
ad this parameters to the start script then works this driver with bond configuration too.
Thanks....

/etc/rc.network restart
sleep 5

**Comment by bb-qq** [comment]
What changes do you wish to make to the driver?

**Comment by bb-qq** [comment]
Alternatively, you can add the command to task scheduler in the control panel.

**Comment by megabyte0469** [comment]
> What changes do you wish to make to the driver?

i have a startscript here with

/etc/rc.network restart
sleep 5

thats all.....

**Comment by megabyte0469** [comment]
bond configuration works here without any problems
