### ISSUE TITLE
Any chance to activate WOL Support?

### ISSUE THREAD

**Issue by HebeROF** [bb-qq/r8152#178]
Driver runs great! Thanks so far :) 

Is there any way to activate Wake on LAN? 
I can only see LAN 1 and 2 in Synology Settings? there might be a config file or ssh command 
to enable it?

**Comment by bb-qq** [comment]
You can enable the WOL flag to the eth2 interface by `sudo ethtool -s eth2 wol g`, but I do not confirm whether it works.
If it does not work, Synology hardware may not support waking up by USB devices.

**Comment by HebeROF** [comment]
As I am using the Club 3D ethernet adapter which is WOL certified, I am unfortunately not able to get it to work. Seems like Synology doesn't support WOL over USB.
