### ISSUE TITLE
llano 2.5Gbps USB Ethernet Adapter can't start on Synology 918+

### ISSUE THREAD

**Issue by morongenius** [bb-qq/r8152#179]
I have this llano adapter connected to the front usb port of 918+. It works with 2.5Gbps link speed but does not starts every time the 918+ restarts (it's on daily power on/off schedule), have to manually stop and run the driver in package centre. The installed driver is 2.15.0-1 and 918+ is on DSM 6.2.4. Pls help. Thanks.

**Comment by bb-qq** [comment]
Could you try to replace the startup script with to latest one?

target script: `/var/packages/r8152/scripts/start-stop-status`
latest file: https://github.com/bb-qq/r8152/blob/master/scripts/start-stop-status

**Comment by morongenius** [comment]
apologies but i do not have the skills to do that.

**Comment by bb-qq** [comment]
Try this command:
`curl -o /var/packages/r8152/scripts/start-stop-status https://raw.githubusercontent.com/bb-qq/r8152/master/scripts/start-stop-status`

**Comment by morongenius** [comment]
sorry all these command line is beyond me. not skilled in IT, any other way? thanks.

**Comment by bb-qq** [comment]
Hmm, the easiest way is that update DSM to 7 and use the latest driver...

**Comment by morongenius** [comment]
i have updated to DSM 7 but failed to run and i still need to do the command line thing... how to do the ssh thing? would appreciate any step by step instructions. thanks a million!

**Comment by morongenius** [comment]
I have updated to DSM7 and successfully installed driver 2.15.0-4 but the issue is still not resolved, so I tried the command above but got an error "-sh: sodo: command not found"....

**Comment by Sjekke** [comment]
It's SUDO ...

**Comment by morongenius** [comment]
Thanks all for your help. successfully replaced startup script and now the adapter is active upon NAS restart. Will monitor for a few days and hopefully the issue is resolved. thanks again

**Comment by bb-qq** [comment]
Oh, sorry, that is a typo. I fixed the comment.

Also, the latest version of the driver is 2.15.0-*5* that includes the latest startup script that you downloaded by the curl command. You don't need such a command in the future release.

**Comment by morongenius** [comment]
So far the adapter has been working well now so issue is resolved. Thanks for the help!
