### ISSUE TITLE
DSM 6.2.4 Not installed.

### ISSUE THREAD

**Issue by SergeySergeevitch** [bb-qq/r8152#193]
r8152-cedarview-2.15.0-5.spk DS1513+ DSM 6.2.4 Not installed. The package is intended for version 7.

**Comment by fox0933** [comment]
yes， The package is intended for version 7。
please，pay attention to look out.

DSM 6.2.4  need use to old version

**Comment by SergeySergeevitch** [comment]
Installed. My adapter is not defined.

https://aliexpress.ru/item/1005002637149626.html?gatewayAdapt=glo2rus&sku_id=12000021520723520

USB\VID_0BDA&PID_8156&REV_3100
USB\VID_0BDA&PID_8156

**Comment by bb-qq** [comment]
Could you fill out [this template](https://github.com/bb-qq/r8152/blob/master/.github/ISSUE_TEMPLATE/custom.md)?

**Comment by bb-qq** [comment]
I close this issue due to no response. Please feel free to reopen the issue when you post additional information.
