### ISSUE TITLE
how to fixed 2 USB devices network cards?

### ISSUE THREAD

**Issue by fuyundaxian** [bb-qq/r8152#198]
i have two USB devices one is 8156,another one is 8152。Every time the device starts up, the network card sequence will be disordered. How to fix the USB device network card？

**Comment by bb-qq** [comment]
It seems that to fix the device name, it would have to be set up in the general Linux manner. I did a little Google searching and found the following page, but I have not tried it.

https://askubuntu.com/questions/1192463/how-to-fix-ethernet-interface-name

**Comment by bb-qq** [comment]
I close this issue due to no response. Please feel free to reopen.
