### ISSUE TITLE
Invalid link in readme.md

### ISSUE THREAD

**Issue by ChaG06** [bb-qq/r8152#199]
### Description of the problem

The link to release page in "Installation" section is pointing to another repo (bb-qq/aqc111/releases).
[https://github.com/bb-qq/aqc111/releases](https://github.com/bb-qq/aqc111/releases) instead of [https://github.com/bb-qq/r8152/releases](https://github.com/bb-qq/r8152/releases)

**Comment by bb-qq** [comment]
Thank you for pointing out the invalid link. I merged the PR.
