### ISSUE TITLE
Easy driver install

### ISSUE THREAD

**Issue by MKVRG99** [bb-qq/r8152#203]
You can allow the installation of the driver using the task scheduler without SSH just set the user as root in the task setting.

and run "install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su"

**Comment by bb-qq** [comment]
Thank you for your proposal, but I would still like to recommend using SSH because it is easier to know the result of the command and diagnose the situation.
