### ISSUE TITLE
DS213Air driver request

### ISSUE THREAD

**Issue by inread** [bb-qq/r8152#206]
I had a Synology DS213Air based on Marvell Kirkwood 88F6282, can you help to update a driver for this type CPU?

Many thanks:

**Comment by ossource** [comment]
I think you should upgrade you NAS first, there is first the RAM issue, than the CPU and than :D

**Comment by bb-qq** [comment]
Sorry, I have decided to cover only the new release DSM 7 compatible devices to reduce support costs. 

There is little hope that the driver will work on these older devices due to lack of performance. As has been pointed out, it will not work on devices with only 256 MB of RAM.
