### ISSUE TITLE
DS1019+ and uGreen 2.5G USB Ethernet Adapter (USB-C and USB3 plug) confirmed work

### ISSUE THREAD

**Issue by transformcube** [bb-qq/r8152#21]
### Description of the problem

DS1019+ and uGreen 2.5G USB Ethernet Adapter (USB-C and USB3 plug) confirmed work

> Replace this line with your answer.

### Description of your products

> - the product name of your NAS model
DS1019+
>     - and output of ``uname -a`` command
4.4.59+
>     - DSM version x.x
DSM 6.2.2-24922 Update 6
> - the product name of the ethernet dongle
uGreen USB3.0 to RJ45 2.5G Ethernet Adapter
https://detail.tmall.com/item.htm?id=616242333868&spm=a1z09.2.0.0.4c152e8dX56A1u&_u=15oamkp2a03&skuId=4343251704751

uGreen USB-C to RJ45 2.5G Ethernet Adapter
https://detail.tmall.com/item.htm?id=607985548355&spm=a1z09.2.0.0.4c152e8dX56A1u&_u=15oamkp3217&skuId=4272714473099

### Description of your environment

> - connect directly to a PC or using a hub
>     - PC: NIC model name or chipset name
>     - Hub: model name
> - cable category (Cat.5e or Cat.6 or Cat.7)
Direct connect to DS1019+ (Cat.6)

### Output of ``dmesg`` command

````
(paste output here)
````

### Output of ``lsusb`` command

````

(paste output here)
````
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.59+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__1-4         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 7F00929AAACA6064)
|__usb2          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.59+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__2-1         0bda:8156:3000 00  3.20 5000MBit/s 512mA 1IF  (Realtek USB 10/100/1G/2.5G LAN 000000001)

### Output of ``ifconfig -a`` command

````
(paste output here)
````
eth0      Link encap:Ethernet  HWaddr
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:130125 errors:0 dropped:0 overruns:0 frame:0
          TX packets:488314 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:12637561 (12.0 MiB)  TX bytes:1650530982 (1.5 GiB)
          Interrupt:112 base 0x6000

eth1      Link encap:Ethernet  HWaddr
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11997 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5531 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4092756 (3.9 MiB)  TX bytes:984619 (961.5 KiB)
          Interrupt:113 base 0x8000

eth2      Link encap:Ethernet  HWaddr
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:41709760 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69123187 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:58157116001 (54.1 GiB)  TX bytes:99661845078 (92.8 GiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5926 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5926 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:836602 (816.9 KiB)  TX bytes:836602 (816.9 KiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by bb-qq** [comment]
Thank you for the report!

**Comment by bb-qq** [comment]
I added this device to the supported list.
