### ISSUE TITLE
D-Link DUB-E250: does not appear in DS716+II Network Interface list, but does appear in USB device list, no connectivity at all

### ISSUE THREAD

**Issue by coyotemax** [bb-qq/r8152#218]
### Description of the problem

Hi,
I managed to install your Braswell driver on my DS716+II with your instructions. Confirmed it's working in Package Center.
2.5GB card i have is D-Link DUB-E250, so I connected it to front port by UNITEK USB 3.0 to USB-C Adapter, max 5Gbps (Model Number: A1034NI). Also I'm using info from this [Issue](https://github.com/bb-qq/r8152/issues/210#issue-1203847790) as it's very similar case.

It's showing in USB list, but no on NIC list in DSM. Both card and usb adapter are working on my windows machine without problems and maintains 2.5GB link. Strange thing, on lsusb it's showed as 480MBit device, maybe USB adapter is faulty?

If I can provide any additional info you need, I will do it ASAP.

Thank you!

### Description of your products

DS716+II
Linux {name] 3.10.108 #42218 SMP Mon Oct 18 19:15:17 CST 2021 x86_64 GNU/Linux synology_braswell_716+II
DSM 7.0.1-42218 Update 3
D-Link DUB-E250, RTL8156b chipset
[Product page](https://us.dlink.com/en/products/dub-e250-usb-c-to-25g-ethernet-adapter)
[Drivers](https://support.dlink.com/ProductInfo.aspx?m=DUB-E250)
[Realtek drivers](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-usb-3-0-software)

### Description of your environment

Connected by TP-Link 2.5GB [TL-SG105-M2](https://www.tp-link.com/en/business-networking/unmanaged-switch/tl-sg105-m2/) switch
PC: RTL8125 NIC 2.5GB
cable category: 5e, about 4 feet long

### Output of ``dmesg`` command

[DS716+II dmesg.txt](https://github.com/bb-qq/r8152/files/8605415/DS716%2BII.dmesg.txt)

### Output of ``lsusb`` command

|__usb1          1d6b:0002:0310 09  2.00  480MBit/s 0mA 1IF  (xhci_hcd 0000:00:14.0) hub
  |__1-2         2001:b301:3100 00  2.10  480MBit/s 200mA 2IFs (D-Link DUBE250 2.5GbE Adapter 001000001)
  |__1-5         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 65006643C0CA6037)
|__usb2          1d6b:0003:0310 09  3.00 5000MBit/s 0mA 1IF  (xhci_hcd 0000:00:14.0) hub
|__usb3          1d6b:0002:0310 09  2.00  480MBit/s 0mA 1IF  (Linux 3.10.108 etxhci_hcd-170202 Etron xHCI Host Controller 0000:04:00.0) hub
|__usb4          1d6b:0003:0310 09  3.00 5000MBit/s 0mA 1IF  (Linux 3.10.108 etxhci_hcd-170202 Etron xHCI Host Controller 0000:04:00.0) hub

### Output of ``ifconfig -a`` command

docker0   Link encap:Ethernet  HWaddr 02:42:50:3F:78:A6
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:11:32:61:12:27
          inet addr:192.168.13.202  Bcast:192.168.13.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3632 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6753 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:354078 (345.7 KiB)  TX bytes:1545458 (1.4 MiB)

eth1      Link encap:Ethernet  HWaddr 00:11:32:61:12:28
          inet addr:169.254.151.155  Bcast:169.254.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:103 errors:0 dropped:0 overruns:0 frame:0
          TX packets:103 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:27802 (27.1 KiB)  TX bytes:27802 (27.1 KiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by bb-qq** [comment]
Certainly it is odd that the USB connection is linked at 480 Mbps. I think it is more likely that there is something wrong with the Type A-C conversion adapter. You might found some thing by trying to reverse the orientation of the Type-C connector.

But then again, I also think it is strange that the device is not recognized. This adapter has been supported since version 2.15.0-7, are you using this version?

**Comment by coyotemax** [comment]
You were absolutely right!! I don't know how I installed 2.15.0- 5 before.
With newest version everything seems to be working OK. lsusb showing 5000MBit/s. Card is visible, getting IP from DHCP. It's working basically. Thank you!! Issue to be closed.
