### ISSUE TITLE
DS216play usb Eth Connection failed

### ISSUE THREAD

**Issue by skyleesea** [bb-qq/r8152#220]
### Description of the problem

> Replace this line with your answer.
DS216play usb Eth Connection failed
Monaco Drv Install - Ok
State - stop (Run click after auto stop)

SSH 
sudo lsusb
USB Eth OK
sudo ifconfig -a
USB Eth None

Help me

### Description of your products

> ds216play
>     
> DSM 7.1-42661 Update 1
> LS-GLAN30R (r8153)

**Comment by bb-qq** [comment]
Could you paste the output of `dmesg`?

**Comment by bb-qq** [comment]
I would like to close this issue since there has been no response. If you have any questions, feel free to re-open it.
