### ISSUE TITLE
r8152-armadaxp-2.15.0-7.spk missing

### ISSUE THREAD

**Issue by motorrad** [bb-qq/r8152#223]
r8152-armadaxp-2.15.0-7.spk missing

>i am sad because r8152-armadaxp-2.15.0-7.spk is missing.

Synology DS214+

**Comment by bb-qq** [comment]
I added the driver for armadaxp.
https://github.com/bb-qq/r8152/releases/tag/2.15.0-9

**Comment by bb-qq** [comment]
I close this issue. If you have any problems, please create a new issue.
