### ISSUE TITLE
DSM 7.x support for armada375?

### ISSUE THREAD

**Issue by mrfreakyt** [bb-qq/r8152#227]
Any chance a spk for the Marvell Armada375 will be updated to DSM 7.1? The last working version is _r8152-armada375-2.15.0-1.spk_ for DSM 6.2.4.

Hardware:
Club 3D USB 3.2 Gen1 Typ-A 2.5G
Synology DS215j

**Comment by bb-qq** [comment]
I uploaded the latest driver for armada375.
https://github.com/bb-qq/r8152/releases/download/2.15.0-8/r8152-armada375-2.15.0-8.spk

**Comment by bb-qq** [comment]
I close this issue. Please create a new issue if you have some problems.
