### ISSUE TITLE
Slow Speeds using Cable Creations 2.5G ethernet to USB adapter - DS920+

### ISSUE THREAD

**Issue by abracadabra1111** [bb-qq/r8152#232]
Recently purchased and installed a cable creations 2.5G ethernet to USB adapter on my DS920+ using the front USB port. Installed the gemini lake drivers listed on the [bb-qq release page](https://github.com/bb-qq/r8152/releases) and everything went smoothly. Synology network page and TP Link switch all show 2.5Gbps connection. But when I run speed tests using iperf or copy files to the NAS, I'm seeing ~1Gbps speeds. Any tips for troubleshooting?

![image](https://user-images.githubusercontent.com/102333980/180518640-a3848042-c2f5-400a-b7af-114ec536349f.png)
![image](https://user-images.githubusercontent.com/102333980/180518656-c75515b7-1f41-4f91-b653-d4f164804f88.png)

**Comment by Sjekke** [comment]
What type is your switch? (See problem here https://github.com/bb-qq/r8152/issues/180#issuecomment-1011055172)

**Comment by abracadabra1111** [comment]
TL-SG3210XHP-M2

**Comment by abracadabra1111** [comment]
> What type is your switch? (See problem with TP Link TL-SG108-M2 here [#180 (comment)](https://github.com/bb-qq/r8152/issues/180#issuecomment-1011055172))

TL-SG3210XHP-M2

**Comment by abracadabra1111** [comment]
Device is working properly. The two devices 2.5Gbps devices were on different VLANs and the router is limited to 1Gbps ports. Placing both devices on same VLAN resulted in proper speed.
![image](https://user-images.githubusercontent.com/102333980/180580775-05fb86e7-94cb-4aa2-9eab-97f599a24f18.png)
