### ISSUE TITLE
Package in error state with DSM 7.1.1

### ISSUE THREAD

**Issue by codex125** [bb-qq/r8152#241]
### Description of the problem

It isn't possible to get the package running after updating to DSM 7.1.1
I used version 2.15.0-7 before updating DSM and tried 2.15.0-10 and 2.16.3-1 after the update.
Both versions gave an error at the installation and the NIC isn't shown in the system settings.

### Description of your products

DS218+
DSM 7.1.1-42962 
Club 3D CAC-1420
![image](https://user-images.githubusercontent.com/112873933/188454188-12675ad4-9427-485a-83eb-29a4d639780e.png)
![image](https://user-images.githubusercontent.com/112873933/188454207-3acc5549-94c9-4df1-bcfe-e53d96f627a0.png)

**Comment by mrjohnpoz** [comment]
Did you run the sudo command, I just updated to 7.1.1 and had the same thing just run the listed sudo command again and all working as before.

**Comment by codex125** [comment]
That worked, thank you very much!
Stupid that I have not tried that.
