### ISSUE TITLE
920+ 7.1.1

### ISSUE THREAD

**Issue by s128300901** [bb-qq/r8152#251]
sergey@synology:~$ sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su
install: cannot stat '/var/packages/r8152/target/r8152/spk_su': No such file or directory

**Comment by bb-qq** [comment]
Try the procedure again from the beginning.

Uninstall package -> Install package -> Run above command -> Install package

If this does not work for you. please paste `/var/log/synopkg.log` here.

**Comment by BlackBird11** [comment]
for me the driver also didn't work anymore
uninstalled -> rebooted -> installed newest -> failed -> copied command from above -> driver sucessfully running

unfortunately it still is not working with the adapter for me. i just can't access my nas

NAS: 918+ (apollolake)

**Comment by bb-qq** [comment]
In the case of the driver successfully running, it is another issue. 
Please create a new issue with `/var/packages/r8152/var/log/start-stop-status.log` (need update to [2.16.3-2](https://github.com/bb-qq/r8152/releases/tag/2.16.3-2))

**Comment by saquibmian** [comment]
This is happening for me, too.

Output of `/var/log/snypkg.log`:
```
2023/01/12 14:39:39 Use given volume to install, volume=[]
2023/01/12 14:39:39 Use any available volume to install, volume=[/volume1]
```
I am running DSM 7.1.1.-42962 Update 2.

**Comment by bb-qq** [comment]
Are you using Safari?
There have been reports of problems with Safari regarding package installation.

**Comment by saquibmian** [comment]
I was able to install the package using `synopkg`.

**Comment by bb-qq** [comment]
It appears that not everyone has been able to resolve the issue, but since there seems to be no response, I will close it.

If you encounter similar problems, please create a new issue with information such as the browser you are using.
