### ISSUE TITLE
Adapter disconnects on DSM 7.1.1 + 2.16.3-2 

### ISSUE THREAD

**Issue by Payn** [bb-qq/r8152#257]
### Description of the problem

I recently upgraded to DSM 7.1.1 and 2.16.3-2 and it started behaving abnormally.
When i shut down my PC, next time i boot up, my NAS network share in windows is disconnected. I have to go into Package Center, find r8152 driver and restart it every time.

Also my previous issue started happening again, see https://github.com/bb-qq/r8152/issues/145#issuecomment-1282215155
Currently auto-negotiation cannot be turned off on NAS like i wrote in above comment, not sure if it can have any effect on this issue.

PC have to be turned off for several hours for this to happen. Maybe the adapter goes into some sleep mode and not waking up?

Here is `/var/packages/r8152/var/log/start-stop-status.log` output: https://pastebin.com/JdchLVvL

### Description of your products

> - Synology DS416play
>     - Linux NAS 3.10.108 #42962 SMP Tue Sep 20 22:34:21 CST 2022 x86_64 GNU/Linux synology_braswell_416play
>     - DSM version 7.1.1-42962
> - USB adapter: https://github.com/bb-qq/r8152/issues/135#issuecomment-893837661

### Description of your environment

> - connected directly to a PC 
>     - PC: ASUS ROG Strix X570-E
> - cable  Cat.6 

### Output of ``lsusb`` command

````

|__usb1          1d6b:0002:0310 09  2.00  480MBit/s 0mA 1IF  (xhci_hcd 0000:00:14.0) hub
  |__1-5         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 6500739047E41695)
|__usb2          1d6b:0003:0310 09  3.00 5000MBit/s 0mA 1IF  (xhci_hcd 0000:00:14.0) hub
  |__2-2         0bda:8156:3100 00  3.20 5000MBit/s 256mA 1IF  (Realtek USB 10/100/1G/2.5G LAN 001000001)
|__usb3          1d6b:0002:0310 09  2.00  480MBit/s 0mA 1IF  (Linux 3.10.108 etxhci_hcd-170202 Etron xHCI Host Controller 0000:04:00.0) hub
|__usb4          1d6b:0003:0310 09  3.00 5000MBit/s 0mA 1IF  (Linux 3.10.108 etxhci_hcd-170202 Etron xHCI Host Controller 0000:04:00.0) hub

````

### Output of ``ifconfig -a`` command

````
eth0      Link encap:Ethernet  HWaddr 00:11:32:6A:F5:81
          inet addr:10.0.0.3  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::211:32ff:fe6a:f581/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:329264 errors:0 dropped:0 overruns:0 frame:0
          TX packets:406365 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:157129490 (149.8 MiB)  TX bytes:134019449 (127.8 MiB)

eth1      Link encap:Ethernet  HWaddr 00:11:32:6A:F5:82
          inet addr:169.254.20.197  Bcast:169.254.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth2      Link encap:Ethernet  HWaddr 00:E0:4C:68:00:63
          inet addr:20.0.0.1  Bcast:20.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::2e0:4cff:fe68:63/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9000  Metric:1
          RX packets:31207 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32751 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8333226 (7.9 MiB)  TX bytes:26768409 (25.5 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:816818 errors:0 dropped:0 overruns:0 frame:0
          TX packets:816818 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:260760652 (248.6 MiB)  TX bytes:260760652 (248.6 MiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

````

**Comment by mr-kek** [comment]
I'm having a similar issue.
Every time I've rebooted the 918+ it just looses connection. 
It shows as connected on DSM, but it's not.
Restarting the driver doesn't work.
I change the IP address and it works. 
Worked fine with an older version of the driver

**Comment by mr-kek** [comment]
I do not have mine set as preferred gateway, as I have a direct connection with my backup nas over the 2.5Gb.

**Comment by bb-qq** [comment]
If you have not configured the adapter as a preferred gateway, then the workaround that came in with 2.16.3-2 should work, so it must be a different issue. Please create a new Issue and attach the logs and other information there.

**Comment by bb-qq** [comment]
I would like to close this issue, although I have not heard a response, as the measures are in place for the first problem of this issue.

As for the second problem, which occurs on an independent network, I cannot investigate further without the results of `ifconfig -a` or `netstat -r`. If you wish to continue the investigate, please create a new issue.
