### ISSUE TITLE
Driver for DS413j CPU Marvell Kirkwood 88F6282

### ISSUE THREAD

**Issue by ctrlaltdelete007** [bb-qq/r8152#260]
### Description of the problem

Is there any possibility to release a .spk for Marvell Kirkwood 88F6282 CPU?

### Description of your products

DS413j CPU Marvell Kirkwood 88F6282
Linux DS413j 2.6.32.12 #25556 Thu Jul 1 14:25:48 CST 2021 armv5tel GNU/Linux synology_88f6282_413j
DSM 6.2.4-25556 Update 5

CLUB 3D

### Description of your environment

direct connection CAT 7

### Output of ``dmesg`` command

````
(paste output here, or attach as a file)
````

### Output of ``lsusb`` command

````
(paste output here)
````

### Output of ``ifconfig -a`` command

````
(paste output here)
````

**Comment by bb-qq** [comment]
Unfortunately, Synology no longer supports this model and does not provide an SDK for development, so I cannot create a driver for it. 
Also, the CPU in this model is very powerless and the drivers will not work well.
