### ISSUE TITLE
DS218 report: working partially :(

### ISSUE THREAD

**Issue by andrus2049** [bb-qq/r8152#264]
Synology DS218
Realtek RTD1296 SoC
DSM 7.1.1-42962 Update 2

USB model:
Wavlink USB 10/100/1G/2.5G LAN - Realtek Semiconductor Corp. VID:0bda PID:8156 REV:31.04

USB 2.5G Ethernet Adapter, WAVLINK USB C to RJ45 2500 Mbps Network adapter with USB 3.0 Adapter,2-in-1 Adapter Compatible with Windows,Mac OS,Linux
https://www.amazon.co.uk/Ethernet-Compatible-Thunderbolt-Aluminum-Portable/dp/B09K7R2K5T

USB 3 port used: on the back
Working reliably, no interruptions during transfer of large GB files.
Speed between DS218 and a PC with another USB 2.5G Ethernet Adapter: about 160 MBs.

Details:

With driver 2.16.3-1 DSM7.x
[r8152-rtd1296-2.16.3-1.spk](https://github.com/bb-qq/r8152/releases/download/2.16.3-1/r8152-rtd1296-2.16.3-1.spk)
Working only with DHCP assigned IP, if a static IP is assigned in GUI then it's not operative after reboot.

With driver:  2.16.3-2 DSM7.x
[r8152-rtd1296-2.16.3-2.spk](https://github.com/bb-qq/r8152/releases/download/2.16.3-2/r8152-rtd1296-2.16.3-2.spk)
Assigned static IP in GUI correctly working after reboot.

Driver updated simply reinstalling the package, no previous package uninstall.

**UPDATE 2022-11-22**

I was too optimistic...:(
Unfortunately, copying large files from the PC to the NAS always works, but I discovered that if I copy large files from the NAS to the PC, after 10-20 seconds the copy fails and the NAS becomes unreacheable on the network.
The NAS resumes the connectivity if I disconnect the ethernet cable from the USB dongle and reconnect it. 
But this problem occurs again and again when transeferrring large files form the NAS.
Small transfers like simply navigating from the PC in the NAS directory structure doesn't cause the problem.

Tested both with NAS static IP and DHCP assigned IP.
Tested also previous with driver 2.16.3-1 DSM7.x (only in DHCP)

Note: The same problem occurs with my other DS218play NAS.

![5158gyM57DL _AC_SX679_](https://user-images.githubusercontent.com/36678690/202467556-06a051b6-22a6-43dd-9636-58aa8b01bcc3.jpg)

**Comment by bb-qq** [comment]
Topics on rtd1296 are merged into issue #275.
If you notice anything new, please comment there.
