### ISSUE TITLE
DS218play report: working partially :(

### ISSUE THREAD

**Issue by andrus2049** [bb-qq/r8152#266]
After the success (see UPDATE later) with my DS218 I tested also my older DS218play, which differs only for the RAM that in the DS218play is only 1 GB.

Synology DS218play
Realtek RTD1296 SoC
DSM 7.1.1-42962 Update 2

USB model:
Digitus USB Type-C™ Gigabit Ethernet Adapter 2.5G, USB-C™ + USB A (USB3.1/3.0)
https://www.digitec.ch/de/s1/product/digitus-usb-type-c-gigabit-ethernet-adapter-25g-usb-c-usb-a-usb3130-usb-c-usb-31-netzwerkadapter-16185124

USB 3 port used: on the back
Working reliably, no interruptions during transfer of large GB files.
Speed to the DS218 from a NUC Intel with 2.5G Ethernet Adapter: about 140-150 MBs.

Details:

With driver: 2.16.3-2 DSM7.x
[r8152-rtd1296-2.16.3-2.spk](https://github.com/bb-qq/r8152/releases/download/2.16.3-2/r8152-rtd1296-2.16.3-2.spk)
Assigned static IP in GUI is correctly working after reboot.

**Many thanks to [bb-qq](https://github.com/bb-qq)!!!**

**UPDATE 2022-11-22**

I was too optimistic...:(
Unfortunately, copying large files from the PC to the NAS always works, but I discovered that if I copy large files from the NAS to the PC, after 10-20 seconds the copy fails and the NAS becomes unreacheable on the network.
The NAS resumes the connectivity if I disconnect the ethernet cable from the USB dongle and reconnect it. 
But this problem occurs again and again when transeferrring large files form the NAS.
Small transfers like simply navigating from the PC in the NAS directory structure doesn't cause the problem.

Tested both with NAS static IP and DHCP assigned IP.
Tested also previous with driver 2.16.3-1 DSM7.x (only in DHCP)

Note: The same problem occurs with my other DS218 NAS.

<img width="350" alt="digitus" src="https://user-images.githubusercontent.com/36678690/202898535-61455e50-cb87-40ae-9bb0-c8f158b57b16.png">

**Comment by cqwangding** [comment]
Similar issue on my ds220j, copy to Nas work well with 200+MB speed, copy from Nas disconnected immediately.

**Comment by bb-qq** [comment]
There have been many other similar reports on the RTD1296 platform, most likely due to a problem with the USB host controller, for which there is no known workaround at this time.

**Comment by bb-qq** [comment]
Topics on rtd1296 are merged into issue #275.
If you notice anything new, please comment there.
