### ISSUE TITLE
DS218+, DSM7.1.1.42962, r8152-apollolake-2.16.3-3test2.spk and Virtual Machine

### ISSUE THREAD

**Issue by patator100** [bb-qq/r8152#267]
Hello

I'm currently using with success a DriverGenius 2.5Go adapter. Nevertheless, I can't manage to add the adapter to my virtual switch so that I could use the 2.5Go connection for my jeedom virtual machine.
I can correctly see both connections in my network:
![image](https://user-images.githubusercontent.com/63559884/202905877-eb7f47d1-c095-4a16-8ead-4b95b331c943.png)

In the virtual switch, I can only see the Lan1 connection:
![image](https://user-images.githubusercontent.com/63559884/202905946-4659acee-19e9-416a-87f6-7a2dc9246e0a.png)

![image](https://user-images.githubusercontent.com/63559884/202905969-9248e760-313f-4931-b897-b2e5eb9b2c81.png)

**ifConfig -a log**
[ifConfig -a.txt](https://github.com/bb-qq/r8152/files/10049833/ifConfig.-a.txt)

Reading another post, I have tried
sudo ovs-vsctl add-br ovs_eth1
sudo ovs-vsctl add-port ovs_eth1 eth1
sudo ifconfig ovs_eth1 up

result (without surprise):
sudo ovs-vsctl add-br ovs_eth1
    ovs-vsctl: cannot create a bridge named ovs_eth1 because a bridge named ovs_eth1 already exists

sudo ovs-vsctl add-port ovs_eth1 eth1
     ovs-vsctl: cannot create a port named eth1 because a port named eth1 already exists on bridge ovs_eth1

sudo ifconfig ovs_eth1 up

Any idea how to fix this issue ?
Which other log would you need ?
thanks

**Comment by mrjohnpoz** [comment]
Odd, I see it available on mine.

![usb](https://user-images.githubusercontent.com/11797687/202906849-4c864a75-0753-4f44-92a0-5e5a6b8f0593.jpg)

I am on 7.1.1, but update 2

**Comment by patator100** [comment]
that's weird. It might depends on the 2.5Go adapter driver. 
Have you rebooted your NAS to get the new LAN adapter to appear ?

**Comment by mrjohnpoz** [comment]
I am using the same r8152-apollolake-2.16.3-2.spk driver - I think he released one without test in the name day later or something.  I have never noticed before if I could add that to my vm switch.. Since for me it is direct connection just to my pc - but upon you saying your having a problem I wanted to see if seeing the same thing.  Which I am not, it lists it there to add to new switch in VM network settings.

And yeah is way quicker than 1 gig ;)  I see 2.37gpbs via iperf testing to and from my nas.

**Comment by patator100** [comment]
ouff ! managed to get it working. After rebooting, the magic happened !
![image](https://user-images.githubusercontent.com/63559884/204110359-5d3e1e9e-8c1d-40ea-97ec-7b03ecf787cf.png)

thank for your help !
pat
