### ISSUE TITLE
Version 2.16.3-3 require root access in package manager

### ISSUE THREAD

**Issue by redhook62** [bb-qq/r8152#268]
### Version 2.16.3-3 require root access in package manager

So , how to deploy the spk file with ssh ?

### Description of your products

> - Synology DS420+
>     Linux DiskStation 4.4.180+ #42962 SMP Tue Oct 18 15:07:03 CST 2022 x86_64 GNU/Linux synology_geminilake_420+
>     DSM 7.1.1-42962 Update 2

**Comment by codex125** [comment]
same here

**Comment by myssv** [comment]
I have the same

German message:
![grafik](https://user-images.githubusercontent.com/65643813/203548620-15cba611-8b99-44c9-a3e0-f56f9d25fad4.png)

**Comment by bb-qq** [comment]
Sorry, I uploaded the wrong packages, so I re-uploaded the correct ones. Please re-download the package.

**Comment by redhook62** [comment]
Great !

Installed without any problems.

best regards
