### ISSUE TITLE
Apollolake - Driver doesn't start after reboot - reinstallation doesn't work. 

### ISSUE THREAD

**Issue by hhessel** [bb-qq/r8152#273]
Seems to be a problem in the scripts so Synology suspects that the driver is broken. 

/var/packages/r8152/scripts/start-stop-status: line 15: BOOTPROTO: unbound variable

Version 2.16.3-2 worked fine but broke after a forced reboot (system hung). This affects driver version 2.16.3-3

Log file attached: [r8152.log](https://github.com/bb-qq/r8152/files/10136617/r8152.log)

**Comment by bb-qq** [comment]
Could you try this test release?
https://github.com/bb-qq/r8152/releases/download/2.16.3-3/r8152-apollolake-2.16.3-4test.spk

**Comment by hhessel** [comment]
Thanks @bb-qq - this test release worked for me. Yet again thanks for swift response! Highly appreciated.
