### ISSUE TITLE
Can't perform installation due to empty `/var/packages/` dir

### ISSUE THREAD

**Issue by altokarev** [bb-qq/r8152#280]
Hey there! 👋 

I'm not able to install package due to

```
The operation failed. Please sign in to DSM again and retry.
```
error.

<img width="810" alt="CleanShot 2023-01-18 at 01 13 23@2x" src="https://user-images.githubusercontent.com/28726429/213024413-58ad69bf-1629-428e-881d-834f564311b1.png">

I assume that this behavior is OK, but there is no `r8152` directory appears at my `/var/packages/`. So I can't install anything with `install` command.

DS920+, Gemini Lake, DSM version `7.1.1-42962`, driver release `v2.16.3-3`.

Thanks in advance! 🙏

**Comment by altokarev** [comment]
I guess I figured this out.

The described issue persists only in Safari on Mac, but there are no problems with Chrome and Windows.

I assume this should be added to README in case this is a feature not a bug :)

**Comment by bb-qq** [comment]
I added a warning of  Safari.
