### ISSUE TITLE
Xpenology DS918+ / DSM 6.2.3-25426 Update 3, Static IP cannot work after reboot

### ISSUE THREAD

**Issue by zkevinzh** [bb-qq/r8152#283]
My Xpenology device(DS918+ / DSM 6.2.3-25426 Update 3, RTL8156B adapter ) has the same IP issue like other devices in DSM7.1.1. However, there are some reasons I can't update my device to DSM7. Can you release a new version driver for DSM6.2 devices to solve this problem? Thank you so much!

**Comment by bb-qq** [comment]
I released the latest packages for DSM 6.2.
https://github.com/bb-qq/r8152/releases/tag/2.16.3-4

If you have problems with this package, please create a new issue using the template.
