### ISSUE TITLE
driver

### ISSUE THREAD

**Issue by s128300901** [bb-qq/r8152#293]
can your driver work with two identical usb adapters

**Comment by bb-qq** [comment]
Currently, this driver does not handle the two same adapters well.
Perhaps a combination of adapters from different vendors might work well, but I have not tried it.

**Comment by bb-qq** [comment]
It appears that two identical adapters can be used when the Hotplug feature is enabled. See this comment for details.
https://github.com/bb-qq/r8152/issues/300#issuecomment-1518530441
