### ISSUE TITLE
Not support DSM7.2 BETA

### ISSUE THREAD

**Issue by skysolf** [bb-qq/r8152#294]
synology ds920+
dsm version: 7.2 beta

not support on dsm 7.2,please fix it.tks.

**Comment by Sjekke** [comment]
> not support on dsm 7.2,please fix it.tks.

Try to stay polite. And why should he support a beta that can change tomorrow.

**Comment by skysolf** [comment]
I don't mean any impoliteness, I just hope that the author can adapt the driver of version 7.2, after all, 7.2 will be officially released sooner or later. That's all, sorry if I made you feel rude.

**Comment by MilesTEG1** [comment]
An update for the upcoming DSM 7.2 will be great.
I hope it will come soon enough.

**Comment by peterywong** [comment]
Yes, an update for 7.2 would be awesome and greatly appreciated.

**Comment by MilesTEG1** [comment]
> @skysolf I forked the original and made a DSM 7.2 Version for the DS920+ https://github.com/almir1904/r8152/releases/download/2.16.3-3/r8152-geminilake-2.16.3-3.spk
> 
> ![image](https://user-images.githubusercontent.com/9274444/225649253-567669ee-f106-4286-b478-49aecec46c69.png)

You should do a PR here with your changes :)

**Comment by almir1904** [comment]
@MilesTEG1 I just used the new Toolchain and rebuild the current package.

**Comment by peterywong** [comment]
> @MilesTEG1 I just used the new Toolchain and rebuild the current package. 

Any tips for doing that with ds919+?

**Comment by peterywong** [comment]
> > > @MilesTEG1 I just used the new Toolchain and rebuild the current package.
> > 
> > 
> > Any tips for doing that with ds919+?
> 
> You mean ds1019+? Ds919+ doesn't exist I think ...

Sorry, I meant DS918+

**Comment by peterywong** [comment]
> https://help.synology.com/developer-guide/getting_started/first_package.html
> 
> I used this guide for it.
> 
> This are my commands
> 
> mkdir -p /toolkit apt-get install cifs-utils python3 python3-pip git git clone https://github.com/SynologyOpenSource/pkgscripts-ng cd /toolkit/pkgscripts-ng/ git checkout DSM7.2 ./EnvDeploy -v 7.2 -p geminilake (replace it with your CPU GEN) mkdir source cd source/ git clone https://github.com/bb-qq/r8152.git cd /toolkit/pkgscripts-ng/ ./PkgCreate.py -v 7.2 -p geminilake -c r8152

Thanks

**Comment by peterywong** [comment]
After building the new package for my NAS, I get "invalid file format" with my spk file.
Have you seen this before?

**Comment by peterywong** [comment]
This is what I have in the INFO file
package="r8152"
version="2.16.3-3"
maintainer="bb-qq"
arch="apollolake"
install_type="package"
thirdparty="yes"
description="Realtek RTL8152/RTL8153 Based USB Ethernet Adapters driver."
displayname="RTL8152/RTL8153 driver"
extractsize="1564"
toolkit_version="63133"
create_time="20230316-23:44:48"

**Comment by skysolf** [comment]
> @skysolf 
> 
> I forked the original and made a DSM 7.2 Version for the DS920+ 
> 
> https://github.com/almir1904/r8152/releases/download/2.16.3-3/r8152-geminilake-2.16.3-3.spk
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/9274444/225649253-567669ee-f106-4286-b478-49aecec46c69.png)
> 
> 

Awesome，tks a lot

**Comment by TheS1R** [comment]
Is this working for you with DSM 7.2 on DS918+? I have DS718+ (_also apollolake_), but I have held off on updating to DSM 7.2 until the driver works.

**Comment by peterywong** [comment]
> Is this working for you with DSM 7.2 on DS918+? I have DS718+ (_also apollolake_), but I have held off on updating to DSM 7.2 until the driver works.

Yes, It's working on my DS918+ with 7.2 beta.

**Comment by noblemd00** [comment]
I used almir1904's file to install the package on a DS1520+ (also geminilake processor) and it worked like a charm. Thanks!

I hope to do what you did for the r8152 for the 5G AQC111 adapter (also by bb-qq). which worked on my 1520 before DSM 7.2 .

**Comment by TheS1R** [comment]
@peterywong Your apollolake image works for me as well on two different DS718+ units. Thanks for doing the legwork and saving me tons of time!

**Comment by halden2714** [comment]
> Here's my build for DS918+ https://github.com/peterywong/r8152/releases/download/2.16.3-3/r8152-apollolake-2.16.3-3.spk

Your build works like a charm for me on DS418Play!!! Much obliged... :)))

**Comment by bb-qq** [comment]
Thank you for trying everything about DSM7.2. 
I created packages based on this information, so if you are using DSM7.2, please try this.
https://github.com/bb-qq/r8152/releases/tag/2.16.3-4

**Comment by blasiusx** [comment]
Thank you very much, bb-qq, and all others. :-)

**Comment by ganyuansi** [comment]
> Thank you for trying everything about DSM7.2. I created packages based on information on this issue. Please try this and let me know if it works. https://github.com/bb-qq/r8152/releases/tag/2.16.3-4

Thank you,My DS920+ update to DMS 7.2 beta,for test work good!my used [UGREEN USB A to 2.5G Ethernet Adapter]

**Comment by bb-qq** [comment]
Thanks for the report. It seems to be working fine, so I will close this issue.
