### ISSUE TITLE
DS223

### ISSUE THREAD

**Issue by fabien67160** [bb-qq/r8152#297]
Hello, which driver do you have to take for the Realtek RTD1619B?

**Comment by fabien67160** [comment]
Is there anyone who wants to answer?

**Comment by bb-qq** [comment]
I created a driver for RTD1619B platforms.
https://github.com/bb-qq/r8152/releases/download/2.16.3-4/r8152-rtd1619b-2.16.3-4_7.1.spk

I hope you will try it and report back with your results.

**Comment by angelgfoto** [comment]
hey bb-qq, what model of adapter is it specifically for, this driver?

**Comment by TheS1R** [comment]
[https://github.com/bb-qq/r8152/wiki/Compatibility](url)

**Comment by bb-qq** [comment]
It seems to have worked successfully, so I would close this issue.

After using it for a while and being able to evaluate its stability, I would be happy to have you report back to me again on this issue.
https://github.com/bb-qq/r8152/issues/135
