### ISSUE TITLE
How to update to DSM 7.2 on a machine with version 2.16.3-3 installed?

### ISSUE THREAD

**Issue by LisonFan** [bb-qq/r8152#309]
I am using a DS718+ device, and the current system version is DSM 7.1.1-42962 Update 5. I would like to update to DSM 7.2, but I noticed on the r8152 releases page that the spk files for DSM 7.1 and 7.2 are different. I am wondering, if I want to update to DSM 7.2, do I need to first uninstall the current version 2.16.3-3? Or is there a more elegant way to update directly?

**Comment by TheS1R** [comment]
Update the NAS, and then install the new driver on top of the existing one — that worked for me. If you have any issues, simply uninstall/reboot/reinstall.

**Comment by Barlos** [comment]
I just updated my Synology DS716+II from DSM 7.1.1-42962 Update 5 to DSM 7.2-64561. Here is my steps.
1. Uninstall the current 2.5gb NIC driver.
2. backup your NAS config or necessary files. <= which I forget to do.
3. Update DSM 7.2
4. After 1st reboot, NAS will update all the Apps that are currently on the NAS.
5. Login to NAS and make sure CPU usage is back to normal.
6. Install 2.5gb NIC driver for DSM 7.2. <= It showed error on mine.
7.  Enable NAS SSH, login and run the command: sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su
8. reboot your NAS.
9. Make sure 2.5gb driver is enabled in App Center
10. Go to control panel and set your 2.5gb USB NIC IP.
11. You may need to reboot couple times.

**Comment by CharlesJung73** [comment]
1. Connect to both 1G and 2.5G LAN ports

2. Update DSM 7.1 → 7.2

3. Uninstall the r8152 driver for DSM 7.1, which no longer works.

4. Install r8152 v2.16.3-4 driver for DSM 7.2

5. There was an error installing the driver

6. Create a task that runs as root in the Scheduler in Control Panel and run it manually.
   "sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su"

7. Complete the driver installation.

In my case, uninstalling and reinstalling the driver left the network settings intact.

**Comment by B58B30TU1** [comment]
For me I have a DS720+ updated to DSM 7.2 and the new driver didn't work. In DSM it shows the package is not compatible. When I try to run the command it prompted: "install: cannot stat '/var/packages/r8152/target/r8152/spk_su': No such file or directory". Sad.

**Comment by dreimer1986** [comment]
And you updated your driver to the 7.2 version?

**Comment by Barlos** [comment]
Please use the ver. 2.16.3-4
https://github.com/bb-qq/r8152/releases/tag/2.16.3-4

**Comment by B58B30TU1** [comment]
I used the r8152-apollolake-2.16.3-4_7.2.spk in my 720+ with DSM 7.2 it doesn't work

**Comment by B58B30TU1** [comment]
Now I used geminilake package it worked, thanks guys

**Comment by s128300901** [comment]
the open switch service order does not work , you can correct it

**Comment by VAllens** [comment]
> 



> 1. Connect to both 1G and 2.5G LAN ports
> 2. Update DSM 7.1 → 7.2
> 3. Uninstall the r8152 driver for DSM 7.1, which no longer works.
> 4. Install r8152 v2.16.3-4 driver for DSM 7.2
> 5. There was an error installing the driver
> 6. Create a task that runs as root in the Scheduler in Control Panel and run it manually.
>    "sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su"
> 7. Complete the driver installation.
> 
> In my case, uninstalling and reinstalling the driver left the network settings intact.

BOOM !!!
The sixth step was executed on the SSH terminal, and now I cannot access NAS :(

**Comment by s128300901** [comment]
Init support of openvswitch 
![Без имени](https://github.com/bb-qq/r8152/assets/92311879/0fb7cfab-0519-4902-9b9c-d475e2648892)

**Comment by Barlos** [comment]
to VAllens:
go to Control Panel => terminal / SNMP => Terminal: enable SSH => apply

Use any SSH client to connect and login to your NAS (IP)

After success login, copy and paste 
"sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su"

Reboot your NAS and try to connect again. You may need to redo it couple time. Pleasue sure the right pacage has been installed.

**Comment by VAllens** [comment]
> to VAllens: go to Control Panel => terminal / SNMP => Terminal: enable SSH => apply
> 
> Use any SSH client to connect and login to your NAS (IP)
> 
> After success login, copy and paste "sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su"
> 
> Reboot your NAS and try to connect again. You may need to redo it couple time. Pleasue sure the right pacage has been installed.

It's not because there's no open SSH port.
It's because the network card was not properly driven.
@Barlos

**Comment by CarlEdman** [comment]
Brief saga, in case it is of help to anybody:
1. Upgraded to DSM 7.2 like a fool, spent 5 minutes trying to figure out why I couldn't connect via network before realizing that the USB 2.5 gbE must have become out of date.
2. Replugged into regular ethernet port and after repairing and updating all everything is copacetic except the 2.5 gbE.
3. Uninstalled the broken driver and installed the _7,2.spk version.  Unsurprisingly the install fails and repeated 'repair' attempts don't work.
4. Ran the `sudo` line and rebooted.  No joy.  Driver remains in broken state and does not have a repair option.
5. Uninstalled the _7.2.spk driver and reinstalled it.  This time install worked without error or requiring any repairs.
6. Hey presto, everything is good without even requiring an additional reboot!

**Comment by fisheepx** [comment]
> Brief saga, in case it is of help to anybody:
> 
> 1. Upgraded to DSM 7.2 like a fool, spent 5 minutes trying to figure out why I couldn't connect via network before realizing that the USB 2.5 gbE must have become out of date.
> 2. Replugged into regular ethernet port and after repairing and updating all everything is copacetic except the 2.5 gbE.
> 3. Uninstalled the broken driver and installed the _7,2.spk version.  Unsurprisingly the install fails and repeated 'repair' attempts don't work.
> 4. Ran the `sudo` line and rebooted.  No joy.  Driver remains in broken state and does not have a repair option.
> 5. Uninstalled the _7.2.spk driver and reinstalled it.  This time install worked without error or requiring any repairs.
> 6. Hey presto, everything is good without even requiring an additional reboot!

Bingo！A reinstallation is necessary！

**Comment by Barlos** [comment]
Key points:

1. make sure you plug-in a network cable to the built-in network port and have access to it.
2. delete the old package and install the new driver.
3. Run the SSH command
4. reboot your NAS
**important: you may repeat the step 2~4 couple times to make your 2.5GB USB NIC to work.**

Cheers~~~
