### ISSUE TITLE
Schedule script on stutdown

### ISSUE THREAD

**Issue by kleuter** [bb-qq/r8152#316]
Can one schedule a script on shutdown like [described here](https://github.com/007revad/Synology_enable_M2_volume/blob/main/how_to_schedule.md) to run this command automatically (e.g. on DSM updates)?

```
sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su
```

**Comment by bb-qq** [comment]
Sorry for the late reply.

I am not sure how packages that are in the process of being installed are handled at shutdown.(keep or remove?) Also, DSM updates may change the behavior, and I think it would be safer to keep SSH enabled to troubleshoot.

**Comment by bb-qq** [comment]
If you have any questions, feel free to re-open.
