### ISSUE TITLE
Support for Realtek RTD1296 SoC possible?

### ISSUE THREAD

**Issue by StevenSeifried** [bb-qq/r8152#34]
Hello,

first of all: Thank you!
 
Is Support for Realtek RTD1296 SoC e.g. used in the DS218 and DS220j possible?

**Comment by XsplitS** [comment]
It's normalty working. But try.

**Comment by bb-qq** [comment]
Please try this. I would appreciate if you report whether it works.
https://github.com/bb-qq/r8152/releases/download/2.13.0-1/r8152-rtd1296-2.13.0-1.spk
