### ISSUE TITLE
Could you help to release a new version to support monaco in dsm 6.2?

### ISSUE THREAD

**Issue by gengchaogit** [bb-qq/r8152#344]
Hi,

I'm searching all the release note, but not found a release version can be support monaco in dsm 6.2.

https://github.com/bb-qq/r8152/releases/tag/2.17.1

[r8152-monaco-2.17.1-1_7.1.spk](https://github.com/bb-qq/r8152/releases/download/2.17.1/r8152-monaco-2.17.1-1_7.1.spk)
380 KB
Jul 15
[r8152-monaco-2.17.1-1_7.2.spk](https://github.com/bb-qq/r8152/releases/download/2.17.1/r8152-monaco-2.17.1-1_7.2.spk)
360 KB
Jul 15

Not found monaco platform dsm 6.2.

Best regards,
Chao

**Comment by gengchaogit** [comment]
my usb netcard is 8156B

**Comment by bb-qq** [comment]
I added [r8152-monaco-2.17.1-1_6.2.spk](https://github.com/bb-qq/r8152/releases/download/2.17.1/r8152-monaco-2.17.1-1_6.2.spk).

**Comment by gengchaogit** [comment]
Oh, thank you !

**Comment by bb-qq** [comment]
The work has been completed and this Issue is closed. It would be appreciated if you could let us know at [this issue](https://github.com/bb-qq/r8152/issues/135) whether it worked stably.
