### ISSUE TITLE
Potential issues running TWO of the same network adapters?

### ISSUE THREAD

**Issue by Poopypants666** [bb-qq/r8152#349]
Hi. I have had a very easy and problem free install for a few months on a 920+. Today I added another of the same network adapter (asus usb c-2500) and gave it a shot. It does not seem that the USB adapter is recognized at all by my 920. Does not appear in any networking settings / ifconfig etc. 

Curious if running two of the same exact USB adapters on the NAS could/would be problematic. Would it be better to have two different adapters (potentially running of two different drivers)? 

The aforementioned adapter which is not recognized by my 920+, is working / recognized on a Windows 11 machine.  It is displaying green connections lights on the port.  So it's not the adapter. Could be an issue with the hub? I plugged in a bunch of other devices and they all seem to be working fine. I do see green connection lights on the hidden USB adapter in question, so it is working(ish).

Is it better or potentially necessary to have use a different 2.5GBit adapter than the one previously installed?

Edit : I deleted any/all config files having to do with r8152, restarted and attempted another clean install with both of the adapters plugged in directly to front port and back ports (without the USB hub). This time the "new" adapter appeared, while my old adapter was unable to be found. Seems there is something about having two of the same adapters during the installation process OR installing the same adapter at the same exact time. 

Worth a note : I did not have to run any SSH commands or restart for the second install. It did not "fail" as it has done in the past. So there may be some settings or config files sticking around?

**Comment by Poopypants666** [comment]
Hello! I had previous success setting up the built in 2x1GBit LAN ports with Multichannel 3 on my 920+

Then moved to a single 2.5GBit usb adapter via a powered USB hub (which also connects to my UPS and another Synology). No issues there as well. 

In hopes of improving transfer speed and to try Multichannel 3 with 2.5GBit adapters, I purchased the same 2.5GBit adapter today Plugged the adapter into that powered usb data hub and the 920+ does not recognize it. The "old" one still appears, still is working. No issues there. My onboard LAN adapters are also there, working fine but no recognition of the new 2.5 adapter.

Curious if there could/would be issues of having two of the same exact adapters, plugged into the same (powered) usb hub?

The adapter in question is the Asus usb-c2500.

I attempted to clean install the same drivers again via the r1852 github page, but not sure if that would work given it's already a sort of work around (and they were already installed on the machine). That didn't really seem to do anything. I uninstalled the driver, and tried a fresh install, of hopes the Synology would then see BOTH adapters. Sadly not, still just one. 

Fwiw, the newly purchased dongle works / is recognized in a windows 11 machine. So it's not the adapter. Could be an issue with the hub? I plugged in a bunch of other devices and they all seem to be working fine. I do see green connection lights on the hidden USB adapter in question, so it is working(ish). 

Is it better or potentially necessary to have use a different 2.5GBit adapter than the one previously installed? 

Appreciate any help or insight you can lend!

**Comment by bb-qq** [comment]
This topic will help you.
https://github.com/bb-qq/r8152/wiki/Troubleshooting#multiple-identical-devices-do-not-work

**Comment by Poopypants666** [comment]
OMG ! Thank you so much !!  Super appreciated.

Glad I was on the right trail with the identical network devices m!

**Comment by bb-qq** [comment]
This Issue is closed. If you have any questions, feel free to re-open it.
