### ISSUE TITLE
My DS1513+ use the asus usb2.5G is not worked. And the speed is half.

### ISSUE THREAD

**Issue by flypigxyz** [bb-qq/r8152#357]
I install the driver and the nas found the adapter, and show it is 2.5G,but test the speed with iperf3, it only 40MB/s. 

what is the problem??

**Comment by Schockwelle** [comment]
I have maybe the same problem. Check this: https://github.com/bb-qq/r8152/discussions/355

**Comment by bb-qq** [comment]
This is a old issue, so I would like to close it.
If using the latest updated package does not solve the problem, feel free to reopen it.

FYI:
* Recent drivers include performance-enhancing changes.
* The following pages summarize what to check for performance issues.
https://github.com/bb-qq/r8152/wiki/Troubleshooting#performance-issues
