### ISSUE TITLE
D218+ UGREEN USB A to 2.5G(RTL8156)  issue

### ISSUE THREAD

**Issue by ryanchen789** [bb-qq/r8152#36]
Test equipment: DS218 +(DSM 6.2.3 25426), Ugreen USB A to 2.5G (RTL8156), ASUS AX86U

When the network cable is inserted into the 2.5G LAN port of the router, the 2.5G network can be recognized, but it can not work normally.
Unable to Ping, unable to access NAS

When the network cable is inserted into the 1g LAN port of the router, the 1g network can be identified and the NAS can be accessed normally.

**Comment by ryanchen789** [comment]
Test equipment: DS218 +, Ugreen USB a to 2.5G (RTL8156), ASUS AX86U


When the network cable is inserted into the 2.5G LAN port of the router, the 2.5G network can be recognized, but it can not work normally.
Unable to Ping, unable to access NAS

When the network cable is inserted into the 1g LAN port of the router, the 1g network can be identified and the NAS can be accessed normally.

**Comment by liuquan321** [comment]
I have report this problem to AUSU support , thay told me that it would be fixed soon, please be patient.

**Comment by XsplitS** [comment]
Try to configure manually your interface (eth1)

ex: ifconfig eth1 192.x.x.x netmask 255.x.x.x up

**Comment by blackie333** [comment]
Hello guys, thank you a lot for this project.
I have DS218 and the same ugreen adaptor on the way from aliexpress :(
Have you managed to fix the issue ?

**Comment by bb-qq** [comment]
Please try connecting the dongle to your Windows PC to isolate the problem.
I guess this is an auto-negotiation issue of the router and it can be solved by fixing the link-speed manually.

**Comment by seasonsolt** [comment]
> Test equipment: DS218 +(DSM 6.2.3 25426), Ugreen USB A to 2.5G (RTL8156), ASUS AX86U
> 
> When the network cable is inserted into the 2.5G LAN port of the router, the 2.5G network can be recognized, but it can not work normally.
> Unable to Ping, unable to access NAS
> 
> When the network cable is inserted into the 1g LAN port of the router, the 1g network can be identified and the NAS can be accessed normally.

ASUS update it's firmware  v.3.0.0.4.384.9283 , it might helps

**Comment by ryanchen789** [comment]
FIRMWARE v.3.0.0.4.384.9283, WORK WELL,THINK'S VERY MUCH
