### ISSUE TITLE
Can not install on 1819+

### ISSUE THREAD

**Issue by LeBigNasty** [bb-qq/r8152#361]
I can not install the RTL8152/8153 driver packge on 1819+ using r8152-denverton-2.17.1-1_7.2.spk
After going through install process and SSH command, after the cinform settings page, I get a "Failed to repair RTL8152/RTL8153 driver" message.
Using DSM 7.2.1 -69057 Update 3

The device is a and it is recognized as a USB 10/100/1g/2.5g LAN ASUSTek device connected to USB in the General Control panel, but does not show up under Network. 
The device is Asus USB-C2500

**Comment by michaelsargent** [comment]
Did you manually start up the package that you installed?  You will need to do this after you reboot.  If the package RLT8152/RTL8153 Driver is not running, you will not see the Network card.

**Comment by LeBigNasty** [comment]
The package wouldn't install, so can not be manually started.

**Comment by michaelsargent** [comment]
The package looks like it didn't install.  It gives a "failed" message.  Did you see the failed message when trying to install? You should be able to run the command after that.

**Comment by bb-qq** [comment]
Could you paste the output of `dmesg`?

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
