### ISSUE TITLE
could you please make the latest release for the ds3617xs (broadwell) ?

### ISSUE THREAD

**Issue by kpas8288** [bb-qq/r8152#367]
i am still use the old version. 
should use the name like r8152-broadwell-2.17.1-1_6.2.spk 
thank you!

**Comment by bb-qq** [comment]
I created the driver.
https://github.com/bb-qq/r8152/releases/download/2.17.1/r8152-broadwell-2.17.1-1_6.2.spk

**Comment by kpas8288** [comment]
thank you very much!
