### ISSUE TITLE
DS214play & DS218play not quite working random disconnect & limited speed

### ISSUE THREAD

**Issue by lawleo** [bb-qq/r8152#380]
<img width="712" alt="Screenshot 2024-02-26 143042" src="https://github.com/bb-qq/r8152/assets/422471/eb702d92-6a86-423b-bebd-c570d106b0fe">

2.17.2 is a bit better than 2.17.1. but still have problem on both machine
DS218play is unusable
DS214play iperf3 result is good, but still only 80-90MB/s during file copy on 4TB WD raid 1 configuration

Also, for driver 2.17.1, I can only set the MTU to 8000 instead of maximum 9000 from the DSM GUI, not sure why

**Comment by bb-qq** [comment]
> DS214play iperf3 result is good, but still only 80-90MB/s during file copy on 4TB WD raid 1 configuration

Disk transfer rate or CPU may be the bottleneck. In the latter case, enabling SMB v3 may improve the situation.

> Also, for driver 2.17.1, I can only set the MTU to 8000 instead of maximum 9000 from the DSM GUI, not sure why

This is due to the change in receive buffer size; 2.17.1 has a receive buffer of 8k, and the MTU is also limited to this value.

**Comment by lawleo** [comment]
> Disk transfer rate or CPU may be the bottleneck. In the latter case, enabling SMB v3 may improve the situation.

I believe it should be CPU bottleneck because either WD 4TB run on my PC get ~200MB/s.  SMBv3 is enabled by default in Synology NAS, but said to say if I change the MTU other than 1518 on my windows 11 PC with 2.5G network, the mapped network drive will just freeze.  May be the situation will be better if the driver work in DS218play

**Comment by guerravic** [comment]
I confirm that the Realtek RTD1296 cpu disconnects the network at the beginning of the file copy.

**Comment by bb-qq** [comment]
Regading DS214play, the latest drivers have changes that affect performance, so please try it.
Regading DS218play, there are known stability issues. See #275 for more information.

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
