### ISSUE TITLE
SA6400 new chip Epyc7002 should choose which driver? DSM is 7.2.

### ISSUE THREAD

**Issue by jesselashen** [bb-qq/r8152#382]
The new SA6400 | AMD EPYC 7272 model, which driver should we choose to install?

**Comment by flowsasa** [comment]
我也遇到了同样的问题

**Comment by bb-qq** [comment]
I added the driver for epyc7002.
https://github.com/bb-qq/r8152/releases/download/2.17.1-2/r8152-epyc7002-2.17.1-2_7.2.spk

I would appreciate it if let me know whether it works well or not.

**Comment by flowsasa** [comment]
> I added the driver for epyc7002. https://github.com/bb-qq/r8152/releases/download/2.17.1-2/r8152-epyc7002-2.17.1-2_7.2.spk
> 
> I would appreciate it if let me know whether it works well or not.

Perfect,This driver is working on my SA6400.
![SA6400](https://github.com/bb-qq/r8152/assets/94598553/f6a0f6e9-2ab9-4c9e-b7b9-68ec97516afa)
<img width="821" alt="S" src="https://github.com/bb-qq/r8152/assets/94598553/f9e08fab-74f0-4e41-ae99-0b812e44255f">
