### ISSUE TITLE
Suggestion for Updating the biaze KZ13 Product Link to Offer a More Competitive Price

### ISSUE THREAD

**Issue by salemilk** [bb-qq/r8152#398]
Hello,

I'm reaching out on behalf of Digital Zakka, a vendor that also supplies the biaze KZ13 USB Ethernet Adapter. I noticed that your GitHub project recommends a biaze KZ13 adapter, and I'd like to propose an update to the product link that might benefit your audience.

We offer the same biaze KZ13 model at a more competitive price, which could be more appealing to the users visiting your project page. Here's the link to our product for your review:

https://digitalzakka.com/product/biaze-kz13-2-5g-usb-external-network-adapter-rj45-converter-hub-gigabit-wired-network-card/

We believe that updating the link on your project page could enhance the value provided to your users by offering them a more affordable option. Could you please consider replacing the current product link with ours?

Thank you for your time and consideration. I look forward to your response!

Best regards,
Bo

**Comment by bb-qq** [comment]
I could not judge which was the major e-commerce site, so I made sure to list both links together.
