### ISSUE TITLE
8153 problem in DS218+

### ISSUE THREAD

**Issue by williamhx** [bb-qq/r8152#40]
### Description of the problem

> RTL8153 can be successfully recognized in DS218+ control panel after driver installation. However, VMM cannot get this interface. Also, after LEDE launch in VMM, this USB interface just gets lost in control panel as well.

### Description of your products

> DS218+
> DSM 6.2.3-25426 Update 2
> RTL8153 Gigabit Ethernet Adapter (CE-LINK)

**Comment by bb-qq** [comment]
The latest driver does support Open vSwitch(VMM) feature. Try it, please.
