### ISSUE TITLE
 r8152-rtd1296 for 6.2 ?

### ISSUE THREAD

**Issue by RagnarogBZH** [bb-qq/r8152#401]
Is it possible to have a driver for rtd1296 processor for 6.2 DSM version ?

**Comment by bb-qq** [comment]
I added the driver to the 2.18.1 release.
https://github.com/bb-qq/r8152/releases/download/2.18.1-1/r8152-rtd1296-2.18.1-1_6.2.spk

But it will only work stably at a 1Gbps link because many people claim instability at a 2.5Gbps link.
