### ISSUE TITLE
Which Driver Do I Need for DS923+?

### ISSUE THREAD

**Issue by deac05** [bb-qq/r8152#402]
Which Driver Do I Need for DS923+?

### Description of your products

> - the product name of your NAS model: DS923+

>     - DSM version: 7.2
> - the product name of the ethernet dongle: ugreen 2.5gbe usb c adapter

**Comment by bb-qq** [comment]
You are using geminilake platform, so use this:
https://github.com/bb-qq/r8152/releases/download/2.17.1-2/r8152-geminilake-2.17.1-2_7.2.spk
