### ISSUE TITLE
Can IPv6 be disable?

### ISSUE THREAD

**Issue by SiLenCe-WB** [bb-qq/r8152#403]
### Description of the problem

Even if I disable IPv6 from my network interface, when I reboot the system it's back on. How can I disable it permanently from boot?

### Description of your products

> DS418play
> DSM 7.2.1-69057 Update 5
> SABRENT ‎NT-S25G (2.5 gigabit ethernet)
> Driver version 2.17.1-1

**Comment by bb-qq** [comment]
There is no way to disable IPv6 at this time, as the driver does not respect the settings on the DSM side.
Could you please use the task scheduler to work around the problem?

**Comment by SiLenCe-WB** [comment]
I have created a task schedule script that runs this command as root and it works 👍

sysctl -w net.ipv6.conf.all.disable_ipv6=1

**Comment by bb-qq** [comment]
I would like to close the issue as I do not plan to change the driver at this time.
