### ISSUE TITLE
Test with DS720+ (Gemini Lake) successful

### ISSUE THREAD

**Issue by Cretanios** [bb-qq/r8152#42]
### Description of the problem

I simply renamed the line
    arch= "apollolake"
         with
    arch="geminilake"
in the r8152-apollolake-2.13.0-1.spk file with NotePad++ and saved the file.

After Installation on the DS720+ the driver worked well and I have proper LAN connection
(see Daniels Video: https://www.youtube.com/watch?v=AyU7bB7BOsc) 

### Description of your products

- DS720+ with 10GB RAM
- DSM version 6.2.3-25426 Update 2
- 3D CAC-1420 Dongle (USB A)

**Comment by marco712** [comment]
It work on the 920+ thans

**Comment by PatrickPTC** [comment]
PatrickPTC commented 9 minutes ago

try on ds920+ can show the card, but can not transfer data or login in admin page. even in direct link mode or net bridge mode. Nas will drop link, shut down. May I ask when it could work. Thanks.

Anyone who can make it work on 920,is there any special setup or ststus ?  I try lots of time and nas must be hard power off when connect fall, too shame. Hope could use it soon.

**Comment by aoleg** [comment]
DS420+ report: works, not stable after a very short while, the device must be restarted. Removed the driver.

**Comment by Will0822** [comment]
DS920+ report: it fails to work normally, DS920+ will crash, must restart the device and delete the driver to work normally

**Comment by aminebizid** [comment]
I got this message with dmesg
r8152: module verification failed: signature and/or required key missing - tainting kernel

**Comment by Sjekke** [comment]
> I got this message with dmesg
> 
> r8152: module verification failed: signature and/or required key missing - tainting kernel

Did you use the latest driver ...

**Comment by bb-qq** [comment]
I have already created [the driver for geminilake built with the official toolchains](https://github.com/bb-qq/r8152/releases/download/2.14.0-2/r8152-geminilake-2.14.0-2.spk). So I would appreciate it if you try it first and create a new issue using the template for bug report if you have any problems. Thanks.
