### ISSUE TITLE
I don't understand how to make the driver work on the Synology NAS

### ISSUE THREAD

**Issue by mrAlexRus** [bb-qq/r8152#50]
The broadwell driver is installed on the DS3617xs normally (r8152-broadwell-2.12.0-1.spk or r8152-broadwell-2.12.0-3.spk is available), but does not start. In the control panel, the status is "Stopped". The USB module on the RTL8156B chip, manufacturer OPEN-SMART is connected. How do I solve this problem?
PS:
I'm not a good Linux expert. I executed the command "sudo dmesg" and got a lot of lines among which there was an error related to r8152:  version magic '4.4.59+ SMP preempt mod_unload ' should be '3.10.102 SMP mod_unload '  What is this?

**Comment by bb-qq** [comment]
What is the DSM version are you using? It seems that the error caused by version mismatch of the kernel.

**Comment by bb-qq** [comment]
Close this issue due to no response. Please feel free to re-open the issue if you notice my comment.
