### ISSUE TITLE
Realtek 8156 Version 2.14 is on Realtek web site

### ISSUE THREAD

**Issue by tmkmuc** [bb-qq/r8152#54]
Please update the driver, and I will try it once more.

**Comment by bb-qq** [comment]
I uploaded 2.14 driver packages. (but it only supports recent platforms.)

**Comment by LeniReinfe** [comment]
pls bb-qq could you compile to Broadwell ? (Virtual Machine doesn't works with 21-12.0-3) >thk so much!

**Comment by LeniReinfe** [comment]
> I uploaded 2.14 driver packages. (but it only supports recent platforms.)

pls bb-qq could you compile 2.14 to Broadwell ? (Virtual Machine doesn't works with 21-12.0-3) >thk so much!

**Comment by Sjekke** [comment]
Is the latest driver already available for the Braswell platform?

**Comment by bb-qq** [comment]
Unfortunately, the latest Realtek drivers do not support old kernels. Technically we can modify the driver to support old kernels, but I do not have much time for doing that. Sorry...

**Comment by bb-qq** [comment]
Please check: https://github.com/bb-qq/r8152/releases/tag/2.14.0-2
