### ISSUE TITLE
Support RTL8156B chipset

### ISSUE THREAD

**Issue by nab128** [bb-qq/r8152#55]
According to https://forum.odroid.com/viewtopic.php?f=172&t=38713 the B version chipset has much better stability

**Comment by bb-qq** [comment]
I believe the current driver already supports B revision. If your devices didn't work, please report VID/PID with a dmesg log.

**Comment by bb-qq** [comment]
I close this issue due to no response. Please feel free to re-open the issue if you have any comments.
