### ISSUE TITLE
r8152B driver for "old" platforms?

### ISSUE THREAD

**Issue by jampem** [bb-qq/r8152#61]
Hi,

like 1517+ Avoton? I tried with 2.12.0-3 but I got "Unknown version 0x7410" and no new network. Or is it just impossible now because of Realtek?

Some Aliexpress 18€ "B" adapter.  Btw adapter works fine with MBPr 2012, 236MB/s read, 186MB/s write to MacPro.

**Comment by bb-qq** [comment]
Unfortunately, the latest Realtek drivers do not support old kernels. Technically we can modify the driver to support old kernels, but I do not have much time for doing that. Sorry...

**Comment by bb-qq** [comment]
Please check: https://github.com/bb-qq/r8152/releases/tag/2.14.0-2

**Comment by bb-qq** [comment]
Closing. Please create a new issue if you have any problems with this driver.
