### ISSUE TITLE
Unable to create bond of onboard interfaces - workaround available

### ISSUE THREAD

**Issue by stepman0** [bb-qq/r8152#63]
I use this driver on my DS918+ with a Club3D CAC-1420 - it works fine.

I found a minor issue: I tried to create an Bond of my "onboard" interfaces (LAN1, LAN2), which fails with a strange error message (Open vSwitch configuration was changed...).

When I uninstall this driver, the creation of the bond works fine.

So if anybody has this issue: Uninstall this package - create the bond - reinstall the package.

**Comment by bb-qq** [comment]
We have released a driver that supports ovs, so hopefully this workaround is no longer needed. Thank you.
