### ISSUE TITLE
Is the latest driver already available for the Braswell platform?

### ISSUE THREAD

**Issue by LeniReinfe** [bb-qq/r8152#64]
2.14 driver for Broadwell has never made by bb-qq >> I am waiting some Gurus made it for my Nas Xpenology .

**Comment by Sjekke** [comment]
I know ... that why the question..

**Comment by Sjekke** [comment]
Is this channel still active?

**Comment by LeniReinfe** [comment]
I thk this developer channel does not work as a forum. If you have problems
with your connection USB net devices, try to see Zerotier software that
allows remote connections without drivers, ports, masks, etc.etc. and it's
an alternative when your NIC has drivers problems.

**Comment by LeniReinfe** [comment]
Thk bb-qq !! your upgraded (14 broadwel) Realtek Works perfectly

**Comment by bb-qq** [comment]
Thank you for the report. Closing.
