### ISSUE TITLE
Have anyone tried on DSM 7.0?

### ISSUE THREAD

**Issue by neverchance12** [bb-qq/r8152#75]

**Comment by Sjekke** [comment]
DMS 7.0 is still in beta. I thougt it doesn't support USB devices in this beta.

**Comment by Garfield999** [comment]
https://github.com/bb-qq/r8152/issues/68

**Comment by U3DC** [comment]
DMS 7 beta does not allow install *.spk file.

**Comment by BeatSkip** [comment]
I actually got it working :) issue #88

**Comment by bb-qq** [comment]
The latest release supports DSM 7.0.
