### ISSUE TITLE
Can work on DSM 7.0 is fine

### ISSUE THREAD

**Issue by U3DC** [bb-qq/r8152#81]
I upgrade dsm 7.0 but can not work

**Comment by Sjekke** [comment]
Same here

**Comment by U3DC** [comment]
> Same here

I solve it use docker.

**Comment by Sjekke** [comment]
> > Same here
> 
> I solve it use docker.

How did you solve it? I'm running DSM 7 beta in Docker also but I will not see my USB 2,5Gb network card

**Comment by bb-qq** [comment]
The latest release supports DSM 7.0.
Merge to #88.
