### ISSUE TITLE
Could you please make ds1618+ (denverton) version?

### ISSUE THREAD

**Issue by legion7298** [bb-qq/r8152#9]
I really really really.. need ds1618+ Version which is used denverton architecture.
Could you please make ds1618+ (denverton) version?

**Comment by bb-qq** [comment]
I created the package for denverton.
https://github.com/bb-qq/r8152/releases/download/2.12.0-2/r8152-denverton-2.12.0-2.spk

Please let me know whether it worked.

**Comment by legion7298** [comment]
> I created the package for denverton.
> https://github.com/bb-qq/r8152/releases/download/2.12.0-2/r8152-denverton-2.12.0-2.spk
> 
> Please let me know whether it worked.

Yes! It works! Perfectly works. Really Really Thanks. You are my hero ToT

**Comment by HomerJau** [comment]
Hi, 

I'm wondering if you can make a new package to support Synology NAS with C2500 Atom for R8152 devices?

I have a DS2415+ with C2538 Atom and would dearly love to add a USB multi gig USB Ethernet adapter. There's quite a few Synology NAS models with this processor.

THX
Garry

**Comment by HomerJau** [comment]
I just noticed your support the DS2415+ with the acq111. I can use that as I haven't bought a USB/Ethernet adapter yet. Thanks fo your great work on these packages!!

**Comment by bb-qq** [comment]
Closing. Please feel free to re-open the issue.
