### ISSUE TITLE
Adapter missing after reboot-DS 920+

### ISSUE THREAD

**Issue by Joeygu79121** [bb-qq/r8152#94]
### Description of the problem

After system reboot, network missing

### Description of your products

> - the product name of your NAS model
DS920
>     - and output of ``uname -a`` command
>     - DSM version 6.2
> - the product name of the ethernet dongle

### Description of your environment

> - connect directly to a PC or using a hub
>     - PC: NIC model name or chipset name
>     - Hub: model name
> - cable category (Cat.5e or Cat.6 or Cat.7)

### Output of ``dmesg`` command

````
(paste output here)
````

### Output of ``lsusb`` command

````
(paste output here)
````

### Output of ``ifconfig -a`` command

````
(paste output here)
````

**Comment by bb-qq** [comment]
DHCP bug was fixed in release 2.14.0-3. Please feel free to re-open the issue if you still have the issue.
