### ISSUE TITLE
DS918+ DSM 7.0 When to support？

### ISSUE THREAD

**Issue by lai-zai** [bb-qq/r8152#95]
Is there a solution?

**Comment by cesar9270** [comment]
exactly the same request for me

**Comment by cesar9270** [comment]
At least someone made a fork and managed to make it work with DSM 7 beta on DS415
https://github.com/bb-qq/r8152/issues/75#issuecomment-765859421

**Comment by lai-zai** [comment]
> At least someone made a fork and managed to make it work with DSM 7 beta on DS415
> [#75 (comment)](https://github.com/bb-qq/r8152/issues/75#issuecomment-765859421)

Other series seem to have no successful cases

**Comment by bb-qq** [comment]
Duplicate of #26
