### ISSUE TITLE
rtl8156 not work on ds3617xs

### ISSUE THREAD

**Issue by Jung1ePeng** [bb-qq/r8152#99]
Any possible to make the ds3617xs of the braodwell architecture support rtl8156 network cards? plz !

**Comment by bb-qq** [comment]
The driver for the Broadwell platform is already uploaded. Please try this driver.
https://github.com/bb-qq/r8152/releases/download/2.14.0-2/r8152-broadwell-2.14.0-2.spk

If you have any problems, please create a new issue.
